import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAFAF5' },
  header: { borderBottomLeftRadius: 24, borderBottomRightRadius: 24, overflow: 'hidden', elevation: 8 },
  headerGradient: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 24,
    alignItems: 'center',
  },
  headerTitle: { fontSize: 26, fontWeight: '900', color: '#fff', letterSpacing: 1 },
  headerSubtitle: { fontSize: 13, color: '#FFF8E8' },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingHorizontal: 10,
    height: 36,
    width: 150,
    elevation: 2,
  },
  searchInput: { flex: 1, fontSize: 12, color: '#333' },
  greetingContainer: { marginHorizontal: 20, marginTop: 20 },
  greeting: { fontSize: 18, fontWeight: '700', color: '#222' },
  welcomeText: { fontSize: 13, color: '#666', marginTop: 4 },
  sliderImage: {
    width: width * 0.9,
    height: 160,
    borderRadius: 18,
    marginHorizontal: width * 0.05,
    marginVertical: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
  },
  dotsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: -8,
    marginBottom: 8,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 8,
    backgroundColor: '#ccc',
    marginHorizontal: 6,
  },
  dotActive: {
    backgroundColor: '#2E4A0D',
    width: 12,
    height: 12,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    marginHorizontal: 20,
    marginTop: 15,
    marginBottom: 6,
    color: '#000',
  },
  actionsList: { flexDirection: 'row', paddingHorizontal: 15, gap: 12, paddingBottom: 10 },
  actionCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 14,
    alignItems: 'center',
    justifyContent: 'center',
    width: 100,
    height: 100,
    elevation: 3,
  },
  iconBox: { padding: 10, borderRadius: 50, marginBottom: 6 },
  actionText: { fontSize: 12, fontWeight: '600', textAlign: 'center', color: '#222' },
  statsNote: { fontSize: 11, color: '#ff0000ff', marginHorizontal: 20, marginBottom: 6 },
  statsContainer: { flexDirection: 'row', justifyContent: 'space-around', marginHorizontal: 10, marginBottom: 20 },
  statCard: { flex: 1, alignItems: 'center', marginHorizontal: 6, borderRadius: 16, paddingVertical: 16 },
  statValue: { fontSize: 18, fontWeight: 'bold' },
  statLabel: { fontSize: 11, textAlign: 'center' },
  bountyCard: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 16,
    marginHorizontal: 20,
    marginBottom: 12,
    elevation: 3,
    padding: 12,
  },
  bountyImage: { width: 70, height: 70, borderRadius: 12, marginRight: 10 },
  bountyInfo: { flex: 1 },
  bountyTitle: { fontSize: 15, fontWeight: '700', color: '#111' },
  bountySub: { fontSize: 12, color: '#666' },
  bountyReward: { fontSize: 13, color: '#b12e2eff', fontWeight: 'bold', marginTop: 4 },
});